export const waitlistCopy = {
  ar: {
    start: {
      eyebrow: "قائمة انتظار ميثاق",
      title: "ابدأ تسجيل اهتمامك بالزواج الجاد",
      body: "التسجيل في هذه المرحلة يضعك على قائمة الانتظار فقط. لا توجد مطابقة أو مراسلة حالياً.",
      age: "أؤكد أن عمري 18 سنة أو أكثر",
      intent: "أنضم إلى ميثاق بنية جادة للزواج",
      phone: "رقم الهاتف",
      phoneHelp: "اكتب الرقم بصيغة دولية مثل +21891… ولن يظهر لمستخدمين آخرين.",
      submit: "إرسال رمز التحقق",
      sending: "جارٍ الإرسال…",
      identityNote: "التحقق من الهاتف لا يعني التحقق من الهوية.",
      error: "تعذر إرسال الرمز. تحقق من الرقم وحاول مرة أخرى.",
    },
    verify: {
      eyebrow: "تأكيد الهاتف",
      title: "أدخل رمز التحقق",
      body: "أدخل الرمز المكوّن من 6 أرقام الذي أرسلناه إلى هاتفك.",
      code: "رمز التحقق",
      submit: "تأكيد ومتابعة",
      verifying: "جارٍ التحقق…",
      back: "تغيير رقم الهاتف",
      error: "الرمز غير صحيح أو انتهت صلاحيته. حاول مرة أخرى.",
    },
    questionnaire: {
      eyebrow: "استبيان جاد ومختصر",
      title: "ساعدنا على فهم احتياجاتك",
      privacy: "حوالي 3 دقائق • إجاباتك خاصة ولن تظهر للعامة",
      step1: "١ — عنك",
      step2: "٢ — ما الذي تبحث عنه",
      step3: "٣ — الخصوصية والثقة",
      next: "التالي",
      previous: "السابق",
      submit: "حفظ التسجيل",
      saving: "جارٍ الحفظ…",
      success: "تم حفظ معلوماتك بنجاح.",
      error: "تعذر حفظ التسجيل. راجع الإجابات وحاول مرة أخرى.",
    },
  },
  en: {
    start: {
      eyebrow: "Mithaq waitlist",
      title: "Start your serious-marriage registration",
      body: "At this stage you are joining a waitlist only. Matching and messaging are not available yet.",
      age: "I confirm that I am 18 or older",
      intent: "I am joining Mithaq with serious intent for marriage",
      phone: "Phone number",
      phoneHelp: "Use international format such as +21891… Your number will not be shown to other users.",
      submit: "Send verification code",
      sending: "Sending…",
      identityNote: "Phone verification is not identity verification.",
      error: "We could not send the code. Check the number and try again.",
    },
    verify: {
      eyebrow: "Phone verification",
      title: "Enter your verification code",
      body: "Enter the 6-digit code sent to your phone.",
      code: "Verification code",
      submit: "Verify and continue",
      verifying: "Verifying…",
      back: "Change phone number",
      error: "The code is incorrect or expired. Try again.",
    },
    questionnaire: {
      eyebrow: "Short serious-intent questionnaire",
      title: "Help us understand what matters to you",
      privacy: "About 3 minutes • Your answers are private and never public",
      step1: "1 — About you",
      step2: "2 — What you are looking for",
      step3: "3 — Privacy and trust",
      next: "Next",
      previous: "Back",
      submit: "Save registration",
      saving: "Saving…",
      success: "Your information has been saved.",
      error: "We could not save your registration. Review your answers and try again.",
    },
  },
} as const;
