#!/usr/bin/env bash
set -euo pipefail

mkdir -p docs .github/workflows
cat > README.md <<'EOF'
# Mithaq | ميثاق

**تعارف موثّق للزواج الجاد**

This repository contains the production-oriented technical foundation for
Mithaq, an Arabic-first, private marriage-introduction network for serious
adult Libyans in Libya and the diaspora.

## Current milestone

**Milestone 1 — Project Foundation**

This release establishes the framework, design tokens, Arabic/English routing,
RTL/LTR behavior, Supabase client boundaries, automated testing, CI, and a
privacy-conservative PWA shell. It does **not** include registration, phone OTP,
waitlist data, member profiles, matching, photographs, messaging, identity
verification, administration, payments, or other Stage A/Stage B business
features.

## Technical baseline

- Node.js 24 LTS
- pnpm 11.21.0
- Next.js 16 App Router and React 19
- TypeScript strict mode
- Tailwind CSS 4 and shadcn/ui-compatible primitives
- `next-intl` with always-prefixed `/ar` and `/en` routes
- Supabase SSR clients and local Supabase CLI
- Vitest, Testing Library, Playwright, and axe
- Serwist PWA integration for Turbopack

## Prerequisites

Install:

1. Node.js 24 LTS.
2. pnpm 11 (`corepack enable` is recommended).
3. Docker Desktop or a compatible Docker runtime for local Supabase.
4. Git.

## Setup

```bash
corepack enable
pnpm install --frozen-lockfile
cp .env.example .env.local
pnpm icons:generate
```

Use only local or development values in `.env.local`. Never commit that file.

```dotenv
APP_ENV=local
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=<local publishable key from Supabase status>
```

Start local Supabase and read its local publishable key:

```bash
pnpm db:start
pnpm exec supabase status
```

Run the application:

```bash
pnpm dev
```

Open `http://localhost:3000`. The root URL deterministically redirects to
`/ar`; English is available at `/en`.

## Verification commands

```bash
pnpm icons:generate
pnpm format:check
pnpm lint
pnpm typecheck
pnpm test
pnpm build
pnpm test:db
pnpm exec playwright install --with-deps chromium
pnpm test:e2e
```

`pnpm check` runs formatting, linting, type checking, unit tests, and a
production build in that order. Run `pnpm build` before `pnpm test:e2e`, because
the E2E suite starts the production server.

Stop local Supabase when finished:

```bash
pnpm db:stop
```

## PWA privacy boundary

The service worker precaches only build assets and the bilingual offline
fallback. It defines no runtime cache for APIs or Supabase requests and must
never cache authenticated responses, private questionnaire data, profile
information, or protected media. This cache policy must be reviewed again
before authenticated routes are introduced.

The mark in `public/icons` is an original, provisional architectural-threshold
symbol generated by `scripts/generate-pwa-icons.mjs`. It is not a final brand
identity.

## Repository guide

- [`AGENTS.md`](./AGENTS.md) — implementation rules for coding agents.
- [`docs/architecture.md`](./docs/architecture.md) — foundation architecture and
  boundaries.
- [`docs/security-foundation.md`](./docs/security-foundation.md) — security and
  privacy controls.
- [`docs/decision-log.md`](./docs/decision-log.md) — accepted architectural
  decisions.
- [`docs/milestones.md`](./docs/milestones.md) — milestone checklist and gates.
- [`docs/known-risks.md`](./docs/known-risks.md) — unresolved risks.
- [`docs/deferred-features.md`](./docs/deferred-features.md) — features
  intentionally not built.

## Generated database types

Milestone 1 creates no application tables, so no generated database type file
is committed yet. After the first reviewed Stage A migration is added, run:

```bash
pnpm db:types
```

`src/types/database.generated.ts` then becomes authoritative and should be
committed with the migration.
EOF
cat > AGENTS.md <<'EOF'
# Agent instructions

## Product boundary

Mithaq is a serious, privacy-conscious marriage-introduction product, not a
casual dating or entertainment application. Preserve the calm, culturally
respectful visual language. Do not introduce hearts, flames, swiping,
popularity mechanics, manipulative engagement patterns, public directories, or
unsupported claims of identity verification.

## Current scope

The repository is at **Milestone 1 — Project Foundation**. Do not add OTP,
waitlist, profiles, matching, introductions, photos, messaging, family
accounts, admin tools, payments, analytics trackers, or AI features unless a
later milestone is explicitly authorized.

## Engineering rules

- Keep TypeScript strict; do not add `any`, broad casts, `@ts-ignore`, or
  disabled lint rules merely to pass checks.
- Prefer Server Components. Add Client Components only around actual browser
  interaction.
- Keep Arabic and English message keys synchronized.
- Preserve always-prefixed locale routing and Arabic as the deterministic
  default.
- Use logical start/end styling rather than physical left/right styling when
  direction matters.
- Never expose Supabase secret/service-role keys to the browser.
- Do not log phone numbers, tokens, OTPs, cookies, profile answers, or other
  private data.
- Treat RLS and server authorization as independent required controls in later
  milestones.
- Do not add runtime PWA caching for APIs, Supabase, authenticated routes, or
  user data.
- Add or update tests with every behavior change.
- Run `pnpm check`, `pnpm test:db`, and `pnpm test:e2e` before claiming
  completion.

## Source of truth

- `package.json` and `pnpm-lock.yaml` define the toolchain.
- SQL migrations will define the database once Stage A tables begin.
- Generated Supabase database types must be refreshed after schema migrations.
- `docs/decision-log.md` records accepted architecture decisions.
- `docs/milestones.md` defines the current implementation gate.
EOF
cat > docs/architecture.md <<'EOF'
# Architecture — Milestone 1

## Objective

Milestone 1 creates a production-quality foundation that can support the Stage
A trust and waitlist product without prematurely implementing it.

## Runtime boundary

```text
Browser or installed PWA
        |
        v
Vercel / Next.js App Router
  - Server Components by default
  - locale-aware root layouts
  - Route Handlers for machine endpoints
  - future Server Actions for authenticated mutations
        |
        +---- Supabase Auth through @supabase/ssr
        |
        +---- Supabase Postgres with RLS in later milestones
        |
        +---- SMS provider abstraction in Milestone 3
```

## Route model

- `/` redirects to `/ar` through `src/proxy.ts`.
- `/ar` renders server-side `lang="ar"` and `dir="rtl"`.
- `/en` renders server-side `lang="en"` and `dir="ltr"`.
- Locale detection is disabled so browser preferences do not silently replace
  the Arabic default.
- `/~offline`, `/api`, `/serwist`, framework assets, and files with extensions
  bypass locale routing.
- Supabase session refresh will be composed into the same `proxy.ts` in
  Milestone 3; no placeholder authentication behavior exists now.

## Application layers

```text
src/app             routes, layouts, metadata, health and service worker
src/components      reusable UI, layout and PWA interaction
src/i18n            routing, request configuration and locale utilities
src/lib             environment, fonts, Supabase clients and helpers
src/messages        synchronized Arabic and English messages
src/types           generated database types once migrations exist
supabase            local configuration, migrations, seed and database tests
tests/e2e           production-browser acceptance tests
```

Future domain modules belong under `src/features`, with validation and
authorization kept centralized rather than embedded in page components.

## Rendering and data access

- Use Server Components by default.
- Client Components are limited to browser-only behavior such as connectivity,
  service-worker updates, and locale interaction.
- Browser Supabase access uses only the public publishable key.
- The server client uses cookie-aware `@supabase/ssr` plumbing without a
  service-role key or authorization shortcut.
- Stage A mutations will validate input with Zod, validate a current principal
  server-side, and rely on RLS as a second enforcement boundary.

## PWA design

Serwist is exposed through `/serwist/sw.js`. The worker:

- precaches generated application assets and `/~offline`;
- has no runtime cache rules;
- provides a document fallback when navigation fails;
- does not force an update while a user is interacting;
- shows a translated update prompt and reloads only after the user accepts and
  the new worker controls the page;
- clears obsolete precaches through Serwist lifecycle handling.

A manual browser installability review remains a Milestone 5 acceptance item.

## Deployment environments

Use separate Supabase projects and Vercel environments for preview/staging and
production. Local development uses the Supabase CLI. No production credentials
belong in the repository or client bundle.
EOF
cat > docs/security-foundation.md <<'EOF'
# Security and privacy foundation

## Controls implemented in Milestone 1

- Required environment variables are validated with Zod through
  `@t3-oss/env-nextjs`.
- No service-role or other privileged Supabase key exists in client or server
  configuration.
- Supabase browser and server clients are separated.
- The health endpoint returns a fixed, non-sensitive response and
  `Cache-Control: no-store`.
- Foundation-wide headers disable framing and unneeded camera, microphone,
  geolocation, and payment capabilities.
- The service worker has no runtime data cache and does not cache APIs or
  Supabase responses.
- The public foundation collects no registration, profile, photograph,
  identity-document, or analytics data.
- CI uses read-only repository permissions.
- Local environment files and Playwright artifacts are ignored by Git.

## Deliberately not claimed

- Phone verification is not identity verification.
- No Stage A user data or RLS policy exists yet because no application table
  exists.
- A tested Content Security Policy is not present yet.
- PWA manifest presence alone is not treated as proof of installability.
- Screenshot prevention and absolute privacy cannot be promised.

## Required controls before Stage A data collection

Milestone 3 must add:

1. versioned, append-only consent records;
2. authenticated server-side mutations with Zod validation;
3. ownership RLS policies and automated cross-user isolation tests;
4. OTP abuse controls, bot protection, rate limits, and provider-safe errors;
5. data minimization and retention decisions;
6. user withdrawal and deletion workflows;
7. privacy-safe audit events without raw sensitive values.

## Required controls before production launch

Milestone 5 must add and verify:

- a tested Content Security Policy;
- privacy-filtered error monitoring;
- dependency and secret scanning;
- production rate limiting;
- backup and restoration procedures;
- incident ownership and escalation;
- legal/privacy review for launch jurisdictions;
- browser/PWA installation testing;
- action pinning to reviewed commit SHAs.
EOF
cat > docs/decision-log.md <<'EOF'
# Decision log

| ID | Status | Decision | Rationale |
| --- | --- | --- | --- |
| D-001 | Accepted | Stage A validates trust and network viability; Milestone 1 implements no business journey. | Prevents an unsafe dating-style prototype from outrunning trust validation. |
| D-002 | Accepted | Arabic is the deterministic default at `/ar`; English is always prefixed at `/en`. | Makes the Arabic-first promise explicit and testable. |
| D-003 | Accepted | `lang` and `dir` are rendered on the server. | Avoids incorrect initial direction and hydration repair. |
| D-004 | Accepted | Next.js App Router and Server Components are the default architecture. | Minimizes browser JavaScript and centralizes trusted operations. |
| D-005 | Accepted | Supabase uses separate browser/server SSR clients with no service-role key. | Preserves least privilege and prepares for cookie-based authentication. |
| D-006 | Accepted | No ORM is introduced in the foundation. | SQL migrations and generated Supabase types will remain the schema source of truth. |
| D-007 | Accepted | The PWA uses an allowlist-style precache and no runtime API/data caching. | Prevents private data from entering long-lived browser caches. |
| D-008 | Accepted | Supabase Auth session refresh is deferred to Milestone 3. | Avoids fake authentication behavior before the OTP flow exists. |
| D-009 | Accepted | A full Content Security Policy is deferred to Milestone 5. | CSP must be based on real integrations and tested rather than guessed. |
| D-010 | Accepted | Stage A will collect age bands rather than exact birth dates. | Reduces unnecessary sensitive data while supporting validation cohorts. |
| D-011 | Accepted | The provisional PWA mark is generated in-repository from an original threshold/arch motif. | Keeps the build reproducible without implying final brand approval. |
| D-012 | Accepted | First-party validation events are preferred over third-party behavioral advertising trackers. | Sensitive questionnaire behavior should not be disclosed to ad-tech systems. |
EOF
cat > docs/milestones.md <<'EOF'
# Milestones and gates

## Milestone 0 — Product and architecture foundation

- [x] Stage A boundary defined.
- [x] Architecture, schema direction, routes, security model, and visual
  direction recorded.

## Milestone 1 — Project foundation

- [x] Next.js App Router and strict TypeScript.
- [x] Tailwind and shadcn-compatible UI foundation.
- [x] Arabic/English always-prefixed routing.
- [x] Server-rendered RTL/LTR direction.
- [x] Environment validation.
- [x] Supabase browser/server client boundaries.
- [x] Local Supabase configuration and pgTAP smoke test.
- [x] PWA manifest, generated icons, offline fallback, connectivity state, and
  controlled updates.
- [x] Unit and production E2E test suites.
- [x] Read-only CI definition.
- [ ] `pnpm check` passes in CI.
- [ ] `pnpm test:db` passes in CI.
- [ ] `pnpm test:e2e` passes in CI.
- [ ] Manual Arabic and English mobile direction screenshots reviewed.

**Gate:** Do not begin Milestone 2 until all unchecked acceptance items pass.

## Milestone 2 — Public trust website

Planned only: home, how it works, privacy and safety, women, men,
Libya/diaspora, FAQ, policies, contact, and responsive navigation.

## Milestone 3 — Waitlist and OTP

Planned only after Milestone 2: 18+ gate, phone-auth abstraction,
questionnaire, consent history, referral, waitlist status, deletion request,
schema migrations, RLS, and isolation tests.

## Milestone 4 — Admin analytics

Planned: invitation-only administrators, MFA, aggregate funnel/cohort
functions, small-cell suppression, audited exports, and no casual raw-answer
browsing.

## Milestone 5 — Production hardening

Planned: rate limits, bot controls, tested CSP, monitoring, backup/restore,
performance, accessibility review, PWA install inspection, staging, deployment,
and launch checklist.

## Milestone 6 — Controlled Stage A launch

A limited real-user launch measures qualified phone-verified demand, female
participation, questionnaire completion, verification willingness, marriage
timeline, referral rate, viable two-sided cohorts, and safety/privacy incidents.

## Milestone 7 and onward — Private beta gate

Profiles, identity/liveness verification, introductions, photographs,
messaging, family participation, and moderation begin only after an explicit
Stage A go decision.
EOF
cat > docs/known-risks.md <<'EOF'
# Known risks

| Risk | Current position | Next control |
| --- | --- | --- |
| Older mobile browsers | Next.js 16 and Tailwind 4 target modern browsers; older Android WebViews may fail. | Test representative Libya-market devices and define a supported-browser policy before launch. |
| SMS deliverability and cost | No provider is selected and Libya/diaspora delivery has not been measured. | Provider spike and country-by-country deliverability tests in Milestone 3. |
| Legal and privacy obligations | Launch jurisdictions, retention periods, SMS terms, and processor agreements are not approved. | Legal/privacy review before accepting real registrations. |
| Moderation ownership | Incident response, emergency escalation, and safety staffing are not assigned. | Name owners and rehearse procedures before Stage A launch. |
| Small-cohort re-identification | Diaspora cohort combinations can expose individuals even without names. | Aggregate queries and suppress cells below a configurable minimum, initially 10. |
| PWA cache regression | A future feature could accidentally add private routes to runtime caching. | Mandatory cache-policy review before every authenticated milestone. |
| Browser installability | Automated tests verify the manifest, icons, and worker, not every browser's install UI. | Manual Chrome/Android and Safari/iOS inspection in Milestone 5. |
| Content Security Policy | No broad CSP is shipped because actual Stage A integrations are not final. | Build and test the policy against staging integrations in Milestone 5. |
| Provisional brand mark | The generated arch icon is original but not a finalized identity. | Complete brand/legal review before public launch. |
| Google font build dependency | `next/font/google` may require network access during a clean build. | Confirm CI/Vercel reliability; self-host reviewed subsets if needed. |
EOF
cat > docs/deferred-features.md <<'EOF'
# Deferred and rejected features

The following features are intentionally absent from Milestone 1 and must not be
inferred from the foundation UI.

## Stage A, later milestones

- public trust and policy pages;
- 18+ gate;
- phone OTP and returning sessions;
- serious-intention waitlist questionnaire;
- consent history;
- referral attribution;
- waitlist status and deletion request;
- invitation-only aggregate administration.

## Stage B, only after validation

- member profiles and preferences;
- government-ID and liveness verification;
- private photographs and signed access;
- curated introductions and compatibility rules;
- mutual-interest decisions;
- messaging and structured prompts;
- family-member invitations and group conversations;
- blocking, reporting, moderation, suspension, bans, and appeals;
- notifications;
- data export;
- subscriptions and payments.

## Rejected product patterns

- infinite swiping;
- a public member directory;
- public profile photographs;
- open unsolicited direct messaging;
- public likes, comments, followers, rankings, or popularity counts;
- streaks, coins, gifts, flames, or addictive engagement mechanics;
- AI-generated deceptive romantic messages;
- automated claims that an algorithm predicts a successful marriage;
- safety, privacy, blocking, or reporting behind a paywall;
- family control over an adult member without explicit consent;
- screenshot-proof or absolute-security promises.
EOF
cat > .github/workflows/ci.yml <<'EOF'
name: CI

on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  APP_ENV: local
  NEXT_PUBLIC_SITE_URL: http://127.0.0.1:3000
  NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ci-public-placeholder

jobs:
  application:
    name: Application checks
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Run formatting, lint, type, unit, and build checks
        run: pnpm check

      - name: Install Playwright Chromium
        run: pnpm exec playwright install --with-deps chromium

      - name: Run production end-to-end tests
        run: pnpm test:e2e

      - name: Upload mobile reference screenshots
        if: always()
        uses: actions/upload-artifact@v6
        with:
          name: foundation-mobile-screenshots
          path: test-results/foundation-*-mobile.png
          if-no-files-found: ignore
          retention-days: 14

      - name: Upload Playwright report on failure
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: playwright-report
          path: playwright-report
          if-no-files-found: ignore
          retention-days: 14

      # Milestone 5: pin all third-party actions to reviewed full commit SHAs.

  database:
    name: Supabase database smoke test
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Check out the repository
        uses: actions/checkout@v7

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Install Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Start local Supabase
        run: pnpm db:start

      - name: Run pgTAP database tests
        run: pnpm test:db

      - name: Stop local Supabase
        if: always()
        run: pnpm db:stop

      # Milestone 5: pin all third-party actions to reviewed full commit SHAs.
EOF
