from __future__ import annotations

import shutil
import textwrap
from pathlib import Path

ROOT = Path.cwd()

for child in ROOT.iterdir():
    if child.name in {".git", ".bootstrap"}:
        continue
    if child.is_dir():
        shutil.rmtree(child)
    else:
        child.unlink()

FILES: dict[str, str] = {
    ".env.example": r"""
APP_ENV=local
NEXT_PUBLIC_SITE_URL=http://localhost:3000
NEXT_PUBLIC_SUPABASE_URL=http://127.0.0.1:54321
NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY=replace-with-local-publishable-key
""",
    ".gitignore": r"""
# dependencies
/node_modules
/.pnp
.pnp.*

# testing
/coverage
/playwright-report
/test-results

# next.js
/.next
/out

# production
/build

# local environment
.env*
!.env.example

# local Supabase
/supabase/.branches
/supabase/.temp

# misc
.DS_Store
*.pem
*.log

# TypeScript
*.tsbuildinfo
next-env.d.ts

# Vercel
.vercel
""",
    ".prettierignore": r"""
.next
node_modules
playwright-report
test-results
coverage
public/icons/*.png
pnpm-lock.yaml
""",
    ".prettierrc.json": r"""
{
  "plugins": ["prettier-plugin-tailwindcss"],
  "tailwindStylesheet": "./src/app/globals.css",
  "semi": true,
  "singleQuote": false
}
""",
    "package.json": r"""
{
  "name": "mithaq",
  "version": "0.1.0",
  "private": true,
  "description": "Arabic-first product foundation for Mithaq | ميثاق",
  "engines": {
    "node": ">=24 <25"
  },
  "packageManager": "pnpm@11.0.0",
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "eslint . --max-warnings=0",
    "typecheck": "tsc --noEmit",
    "format": "prettier --write .",
    "format:check": "prettier --check .",
    "test": "vitest run",
    "test:watch": "vitest",
    "test:e2e": "playwright test",
    "test:e2e:ui": "playwright test --ui",
    "test:db": "supabase test db",
    "check": "pnpm format:check && pnpm lint && pnpm typecheck && pnpm test && pnpm build",
    "db:start": "supabase start",
    "db:stop": "supabase stop",
    "db:reset": "supabase db reset",
    "db:types": "supabase gen types typescript --local > src/types/database.generated.ts",
    "icons:generate": "node scripts/generate-pwa-icons.mjs"
  },
  "dependencies": {
    "@radix-ui/react-label": "latest",
    "@radix-ui/react-separator": "latest",
    "@radix-ui/react-slot": "latest",
    "@supabase/ssr": "latest",
    "@supabase/supabase-js": "latest",
    "@t3-oss/env-nextjs": "latest",
    "class-variance-authority": "latest",
    "clsx": "latest",
    "lucide-react": "latest",
    "next": "^16.3.0",
    "next-intl": "latest",
    "react": "^19.2.0",
    "react-dom": "^19.2.0",
    "server-only": "latest",
    "sonner": "latest",
    "tailwind-merge": "latest",
    "zod": "latest"
  },
  "devDependencies": {
    "@axe-core/playwright": "latest",
    "@playwright/test": "latest",
    "@serwist/turbopack": "latest",
    "@tailwindcss/postcss": "latest",
    "@testing-library/jest-dom": "latest",
    "@testing-library/react": "latest",
    "@testing-library/user-event": "latest",
    "@types/node": "latest",
    "@types/react": "latest",
    "@types/react-dom": "latest",
    "@vitejs/plugin-react": "latest",
    "eslint": "latest",
    "eslint-config-next": "^16.3.0",
    "jsdom": "latest",
    "prettier": "latest",
    "prettier-plugin-tailwindcss": "latest",
    "serwist": "latest",
    "sharp": "latest",
    "supabase": "latest",
    "tailwindcss": "latest",
    "tw-animate-css": "latest",
    "typescript": "latest",
    "vitest": "latest"
  }
}
""",
    "tsconfig.json": r"""
{
  "compilerOptions": {
    "target": "ES2017",
    "lib": ["dom", "dom.iterable", "esnext"],
    "allowJs": false,
    "skipLibCheck": true,
    "strict": true,
    "noEmit": true,
    "esModuleInterop": true,
    "module": "esnext",
    "moduleResolution": "bundler",
    "resolveJsonModule": true,
    "isolatedModules": true,
    "jsx": "react-jsx",
    "incremental": true,
    "plugins": [{ "name": "next" }],
    "paths": {
      "@/*": ["./src/*"]
    }
  },
  "include": [
    "next-env.d.ts",
    "**/*.ts",
    "**/*.tsx",
    ".next/types/**/*.ts",
    ".next/dev/types/**/*.ts"
  ],
  "exclude": ["node_modules"]
}
""",
    "next-env.d.ts": r"""
/// <reference types="next" />
/// <reference types="next/image-types/global" />

// This file is generated by Next.js. Do not edit it directly.
""",
    "postcss.config.mjs": r"""
const config = {
  plugins: {
    "@tailwindcss/postcss": {},
  },
};

export default config;
""",
    "eslint.config.mjs": r"""
import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

export default defineConfig([
  ...nextVitals,
  ...nextTypeScript,
  globalIgnores([
    ".next/**",
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "public/serwist/**",
  ]),
]);
""",
    "next.config.ts": r"""
import type { NextConfig } from "next";

const securityHeaders = [
  { key: "X-Content-Type-Options", value: "nosniff" },
  { key: "Referrer-Policy", value: "strict-origin-when-cross-origin" },
  { key: "X-Frame-Options", value: "DENY" },
  {
    key: "Permissions-Policy",
    value: "camera=(), microphone=(), geolocation=(), payment=()",
  },
];

const nextConfig: NextConfig = {
  reactStrictMode: true,
  poweredByHeader: false,
  async headers() {
    return [
      {
        source: "/:path*",
        headers: securityHeaders,
      },
    ];
  },
};

export default nextConfig;
""",
    "components.json": r"""
{
  "$schema": "https://ui.shadcn.com/schema.json",
  "style": "new-york",
  "rsc": true,
  "tsx": true,
  "tailwind": {
    "config": "",
    "css": "src/app/globals.css",
    "baseColor": "neutral",
    "cssVariables": true,
    "prefix": ""
  },
  "iconLibrary": "lucide",
  "aliases": {
    "components": "@/components",
    "utils": "@/lib/utils",
    "ui": "@/components/ui",
    "lib": "@/lib",
    "hooks": "@/hooks"
  }
}
""",
    "vitest.config.ts": r"""
import path from "node:path";
import react from "@vitejs/plugin-react";
import { defineConfig } from "vitest/config";

export default defineConfig({
  plugins: [react()],
  resolve: {
    alias: {
      "@": path.resolve(__dirname, "./src"),
    },
  },
  test: {
    environment: "jsdom",
    setupFiles: ["./vitest.setup.ts"],
    env: {
      APP_ENV: "local",
      NEXT_PUBLIC_SITE_URL: "http://localhost:3000",
      NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321",
      NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "test-publishable-key",
    },
    coverage: {
      reporter: ["text", "json", "html"],
    },
  },
});
""",
    "vitest.setup.ts": r"""
import "@testing-library/jest-dom/vitest";
""",
    "playwright.config.ts": r"""
import { defineConfig, devices } from "@playwright/test";

const testEnvironment = {
  APP_ENV: "preview",
  NEXT_PUBLIC_SITE_URL: "http://127.0.0.1:3000",
  NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "test-publishable-key",
};

export default defineConfig({
  testDir: "./tests/e2e",
  fullyParallel: true,
  forbidOnly: Boolean(process.env.CI),
  retries: process.env.CI ? 2 : 0,
  workers: process.env.CI ? 1 : undefined,
  reporter: process.env.CI ? "github" : "list",
  use: {
    baseURL: "http://127.0.0.1:3000",
    trace: "on-first-retry",
  },
  projects: [
    {
      name: "chromium",
      use: { ...devices["Desktop Chrome"] },
    },
  ],
  webServer: {
    command: "pnpm build && pnpm start",
    url: "http://127.0.0.1:3000/ar",
    reuseExistingServer: !process.env.CI,
    timeout: 240_000,
    env: testEnvironment,
  },
});
""",
    "scripts/generate-pwa-icons.mjs": r"""
import { mkdir } from "node:fs/promises";
import path from "node:path";
import sharp from "sharp";

const outputDirectory = path.join(process.cwd(), "public", "icons");
await mkdir(outputDirectory, { recursive: true });

function thresholdMark(size, maskable = false) {
  const padding = maskable ? Math.round(size * 0.16) : Math.round(size * 0.08);
  const inner = size - padding * 2;
  const stroke = Math.max(8, Math.round(size * 0.045));
  const archTop = padding + Math.round(inner * 0.16);
  const archBottom = padding + Math.round(inner * 0.82);
  const left = padding + Math.round(inner * 0.22);
  const right = padding + Math.round(inner * 0.78);
  const radius = (right - left) / 2;

  return Buffer.from(`
    <svg xmlns="http://www.w3.org/2000/svg" width="${size}" height="${size}" viewBox="0 0 ${size} ${size}">
      <rect width="${size}" height="${size}" rx="${Math.round(size * 0.18)}" fill="#0F4D3F"/>
      <path d="M ${left} ${archBottom} V ${archTop + radius} A ${radius} ${radius} 0 0 1 ${right} ${archTop + radius} V ${archBottom}" fill="none" stroke="#F8F4EA" stroke-width="${stroke}" stroke-linecap="round"/>
      <path d="M ${size / 2} ${archTop + radius} V ${archBottom}" fill="none" stroke="#A98342" stroke-width="${Math.max(5, Math.round(stroke * 0.55))}" stroke-linecap="round"/>
      <circle cx="${size / 2}" cy="${archBottom}" r="${Math.round(stroke * 0.38)}" fill="#F8F4EA"/>
    </svg>
  `);
}

const icons = [
  { name: "icon-192.png", size: 192 },
  { name: "icon-512.png", size: 512 },
  { name: "icon-maskable-512.png", size: 512, maskable: true },
  { name: "apple-touch-icon.png", size: 180 },
];

await Promise.all(
  icons.map(({ name, size, maskable = false }) =>
    sharp(thresholdMark(size, maskable)).png().toFile(path.join(outputDirectory, name)),
  ),
);

console.log(`Generated ${icons.length} provisional Mithaq PWA icons.`);
""",
    "supabase/config.toml": r"""
project_id = "mithaq"

[api]
enabled = true
port = 54321
schemas = ["public", "graphql_public"]
extra_search_path = ["public", "extensions"]
max_rows = 1000

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1"

[inbucket]
enabled = true
port = 54324

[storage]
enabled = false
file_size_limit = "50MiB"

[auth]
enabled = true
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["http://localhost:3000"]
jwt_expiry = 3600
enable_signup = false
enable_anonymous_sign_ins = false

[auth.email]
enable_signup = false
double_confirm_changes = true
enable_confirmations = false

[analytics]
enabled = false
""",
    "supabase/seed.sql": r"""
-- Milestone 1 intentionally creates no application data.
-- Stage A schema and reference data begin in Milestone 3.
""",
    "supabase/tests/database/000_smoke.sql": r"""
begin;

select plan(1);
select has_schema('public', 'the local database exposes the public schema');
select * from finish();

rollback;
""",
    "src/i18n/routing.ts": r"""
import { defineRouting } from "next-intl/routing";

export const routing = defineRouting({
  locales: ["ar", "en"],
  defaultLocale: "ar",
  localePrefix: "always",
  localeDetection: false,
});

export type AppLocale = (typeof routing.locales)[number];

export function isAppLocale(value: string): value is AppLocale {
  return routing.locales.some((locale) => locale === value);
}

export function directionForLocale(locale: AppLocale): "rtl" | "ltr" {
  return locale === "ar" ? "rtl" : "ltr";
}

export function alternateLocale(locale: AppLocale): AppLocale {
  return locale === "ar" ? "en" : "ar";
}
""",
    "src/i18n/navigation.ts": r"""
import { createNavigation } from "next-intl/navigation";
import { routing } from "./routing";

export const { Link, redirect, usePathname, useRouter, getPathname } =
  createNavigation(routing);
""",
    "src/i18n/request.ts": r"""
import { getRequestConfig } from "next-intl/server";
import { isAppLocale, routing } from "./routing";

export default getRequestConfig(async ({ requestLocale }) => {
  const requestedLocale = await requestLocale;
  const locale =
    requestedLocale && isAppLocale(requestedLocale)
      ? requestedLocale
      : routing.defaultLocale;

  return {
    locale,
    messages: (await import(`../messages/${locale}.json`)).default,
  };
});
""",
    "src/proxy.ts": r"""
import createMiddleware from "next-intl/middleware";
import { routing } from "@/i18n/routing";

// Milestone 3 will compose this locale proxy with Supabase session refresh.
// Until then it deliberately performs no authentication work.
export default createMiddleware(routing);

export const config = {
  matcher: ["/((?!api|serwist|~offline|_next|_vercel|.*\\..*).*)"],
};
""",
    "src/messages/ar.json": r"""
{
  "Metadata": {
    "title": "ميثاق | تعارف موثّق للزواج الجاد",
    "description": "الأساس التقني العربي أولاً لشبكة ميثاق الخاصة والجادّة للتعارف بغرض الزواج."
  },
  "Foundation": {
    "eyebrow": "المرحلة الأولى — الأساس التقني",
    "title": "ميثاق",
    "latinName": "Mithaq",
    "tagline": "تعارف موثّق للزواج الجاد",
    "status": "نعمل حالياً على إعداد أساس آمن، خاص، وسهل الاستخدام قبل فتح التسجيل.",
    "privacyTitle": "الخصوصية قبل الاكتشاف",
    "privacyBody": "لا توجد ملفات أعضاء أو صور عامة أو مراسلة في هذه المرحلة. نبني ضوابط الثقة أولاً.",
    "directionTitle": "مصمم للعربية من البداية",
    "directionBody": "الاتجاه من اليمين إلى اليسار جزء من بنية المنتج، وليس تعديلاً بصرياً لاحقاً.",
    "foundationLabel": "حالة المنتج",
    "foundationValue": "الأساس قيد التجهيز",
    "languageAction": "English",
    "languageLabel": "عرض الموقع باللغة الإنجليزية",
    "trustNote": "هذه صفحة تأسيسية ولا تدّعي التحقق من هوية أي مستخدم."
  },
  "Pwa": {
    "offline": "أنت غير متصل بالإنترنت. سنعرض فقط المحتوى العام المتاح دون اتصال.",
    "updateReady": "يتوفر تحديث جديد لميثاق.",
    "updateAction": "تحديث الآن",
    "dismiss": "لاحقاً"
  },
  "Common": {
    "loading": "جارٍ التحميل…",
    "errorTitle": "حدث خطأ غير متوقع",
    "errorBody": "لم نتمكن من إكمال الطلب. حاول مرة أخرى.",
    "retry": "إعادة المحاولة",
    "notFoundTitle": "الصفحة غير موجودة",
    "notFoundBody": "الرابط الذي فتحته غير متاح.",
    "home": "العودة إلى البداية"
  }
}
""",
    "src/messages/en.json": r"""
{
  "Metadata": {
    "title": "Mithaq | Trusted introductions for serious marriage",
    "description": "The Arabic-first technical foundation for Mithaq, a private network for serious marriage introductions."
  },
  "Foundation": {
    "eyebrow": "Milestone 1 — Technical foundation",
    "title": "Mithaq",
    "latinName": "ميثاق",
    "tagline": "Trusted introductions for serious marriage",
    "status": "We are preparing a secure, private and accessible foundation before registration opens.",
    "privacyTitle": "Privacy before discovery",
    "privacyBody": "There are no member profiles, public photos or messaging in this milestone. Trust controls come first.",
    "directionTitle": "Designed for Arabic from the start",
    "directionBody": "Right-to-left behavior is part of the product architecture, not a visual patch added later.",
    "foundationLabel": "Product status",
    "foundationValue": "Foundation in preparation",
    "languageAction": "العربية",
    "languageLabel": "View the site in Arabic",
    "trustNote": "This foundation page makes no claim that any user identity has been verified."
  },
  "Pwa": {
    "offline": "You are offline. Only public content available offline will be shown.",
    "updateReady": "A new Mithaq update is ready.",
    "updateAction": "Update now",
    "dismiss": "Later"
  },
  "Common": {
    "loading": "Loading…",
    "errorTitle": "Something went wrong",
    "errorBody": "The request could not be completed. Please try again.",
    "retry": "Try again",
    "notFoundTitle": "Page not found",
    "notFoundBody": "The page you opened is unavailable.",
    "home": "Return home"
  }
}
""",
    "src/lib/utils.ts": r"""
import { clsx, type ClassValue } from "clsx";
import { twMerge } from "tailwind-merge";

export function cn(...inputs: ClassValue[]) {
  return twMerge(clsx(inputs));
}
""",
    "src/lib/env.ts": r"""
import { createEnv } from "@t3-oss/env-nextjs";
import { z } from "zod";

export const environmentSchema = z.object({
  APP_ENV: z.enum(["local", "preview", "staging", "production"]),
  NEXT_PUBLIC_SITE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_URL: z.string().url(),
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: z.string().min(1),
});

export function validateEnvironment(values: Record<string, string | undefined>) {
  return environmentSchema.parse(values);
}

export const env = createEnv({
  server: {
    APP_ENV: environmentSchema.shape.APP_ENV,
  },
  client: {
    NEXT_PUBLIC_SITE_URL: environmentSchema.shape.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_SUPABASE_URL:
      environmentSchema.shape.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
      environmentSchema.shape.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  },
  runtimeEnv: {
    APP_ENV: process.env.APP_ENV,
    NEXT_PUBLIC_SITE_URL: process.env.NEXT_PUBLIC_SITE_URL,
    NEXT_PUBLIC_SUPABASE_URL: process.env.NEXT_PUBLIC_SUPABASE_URL,
    NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY:
      process.env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  },
  emptyStringAsUndefined: true,
});
""",
    "src/lib/fonts.ts": r"""
import { Inter, Noto_Sans_Arabic } from "next/font/google";

export const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  display: "swap",
});

export const notoSansArabic = Noto_Sans_Arabic({
  subsets: ["arabic"],
  variable: "--font-arabic",
  display: "swap",
  weight: ["400", "500", "600", "700"],
});
""",
    "src/lib/supabase/client.ts": r"""
"use client";

import { createBrowserClient } from "@supabase/ssr";
import { env } from "@/lib/env";

export function createClient() {
  return createBrowserClient(
    env.NEXT_PUBLIC_SUPABASE_URL,
    env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
  );
}
""",
    "src/lib/supabase/server.ts": r"""
import "server-only";

import { createServerClient } from "@supabase/ssr";
import { cookies } from "next/headers";
import { env } from "@/lib/env";

export async function createClient() {
  const cookieStore = await cookies();

  return createServerClient(
    env.NEXT_PUBLIC_SUPABASE_URL,
    env.NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY,
    {
      cookies: {
        getAll() {
          return cookieStore.getAll();
        },
        setAll(cookiesToSet) {
          try {
            cookiesToSet.forEach(({ name, value, options }) => {
              cookieStore.set(name, value, options);
            });
          } catch {
            // Server Components cannot set cookies. Milestone 3 performs refresh in proxy.ts.
          }
        },
      },
    },
  );
}
""",
    "src/types/README.md": r"""
# Generated database types

Milestone 1 intentionally defines no application tables. After the Stage A migration is introduced, run `pnpm db:types` and treat `database.generated.ts` as the authoritative database type definition.
""",
    "src/components/ui/button.tsx": r"""
import * as React from "react";
import { Slot } from "@radix-ui/react-slot";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const buttonVariants = cva(
  "inline-flex min-h-11 items-center justify-center gap-2 rounded-xl text-sm font-semibold whitespace-nowrap transition-colors outline-none focus-visible:ring-2 focus-visible:ring-ring focus-visible:ring-offset-2 focus-visible:ring-offset-background disabled:pointer-events-none disabled:opacity-50",
  {
    variants: {
      variant: {
        default: "bg-primary text-primary-foreground hover:bg-primary/90",
        outline:
          "border border-border bg-background text-foreground hover:bg-muted",
        ghost: "text-foreground hover:bg-muted",
        destructive:
          "bg-destructive text-destructive-foreground hover:bg-destructive/90",
      },
      size: {
        default: "h-11 px-5 py-2",
        sm: "h-11 px-4",
        lg: "h-12 px-7 text-base",
        icon: "size-11",
      },
    },
    defaultVariants: {
      variant: "default",
      size: "default",
    },
  },
);

function Button({
  className,
  variant,
  size,
  asChild = false,
  ...props
}: React.ComponentProps<"button"> &
  VariantProps<typeof buttonVariants> & { asChild?: boolean }) {
  const Component = asChild ? Slot : "button";

  return (
    <Component
      data-slot="button"
      className={cn(buttonVariants({ variant, size, className }))}
      {...props}
    />
  );
}

export { Button, buttonVariants };
""",
    "src/components/ui/card.tsx": r"""
import * as React from "react";
import { cn } from "@/lib/utils";

function Card({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card"
      className={cn(
        "rounded-2xl border border-border bg-card text-card-foreground shadow-sm",
        className,
      )}
      {...props}
    />
  );
}

function CardHeader({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-header"
      className={cn("grid gap-2 p-6", className)}
      {...props}
    />
  );
}

function CardTitle({ className, ...props }: React.ComponentProps<"h2">) {
  return (
    <h2
      data-slot="card-title"
      className={cn("text-xl font-semibold leading-none", className)}
      {...props}
    />
  );
}

function CardDescription({ className, ...props }: React.ComponentProps<"p">) {
  return (
    <p
      data-slot="card-description"
      className={cn("text-sm leading-6 text-muted-foreground", className)}
      {...props}
    />
  );
}

function CardContent({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="card-content"
      className={cn("px-6 pb-6", className)}
      {...props}
    />
  );
}

export { Card, CardHeader, CardTitle, CardDescription, CardContent };
""",
    "src/components/ui/input.tsx": r"""
import * as React from "react";
import { cn } from "@/lib/utils";

function Input({ className, type, ...props }: React.ComponentProps<"input">) {
  return (
    <input
      type={type}
      data-slot="input"
      className={cn(
        "flex min-h-12 w-full rounded-xl border border-input bg-background px-3 py-2 text-base text-foreground shadow-sm outline-none placeholder:text-muted-foreground focus-visible:ring-2 focus-visible:ring-ring disabled:cursor-not-allowed disabled:opacity-50 md:text-sm",
        className,
      )}
      {...props}
    />
  );
}

export { Input };
""",
    "src/components/ui/label.tsx": r"""
"use client";

import * as React from "react";
import * as LabelPrimitive from "@radix-ui/react-label";
import { cn } from "@/lib/utils";

function Label({ className, ...props }: React.ComponentProps<typeof LabelPrimitive.Root>) {
  return (
    <LabelPrimitive.Root
      data-slot="label"
      className={cn(
        "flex items-center gap-2 text-sm font-medium leading-none peer-disabled:cursor-not-allowed peer-disabled:opacity-50",
        className,
      )}
      {...props}
    />
  );
}

export { Label };
""",
    "src/components/ui/alert.tsx": r"""
import * as React from "react";
import { cva, type VariantProps } from "class-variance-authority";
import { cn } from "@/lib/utils";

const alertVariants = cva(
  "relative grid w-full grid-cols-[0_1fr] items-start gap-y-1 rounded-xl border px-4 py-3 text-sm has-[>svg]:grid-cols-[calc(var(--spacing)*4)_1fr] has-[>svg]:gap-x-3",
  {
    variants: {
      variant: {
        default: "bg-card text-card-foreground",
        destructive:
          "border-destructive/40 bg-destructive/5 text-destructive [&>svg]:text-destructive",
      },
    },
    defaultVariants: { variant: "default" },
  },
);

function Alert({
  className,
  variant,
  ...props
}: React.ComponentProps<"div"> & VariantProps<typeof alertVariants>) {
  return (
    <div
      role="alert"
      data-slot="alert"
      className={cn(alertVariants({ variant }), className)}
      {...props}
    />
  );
}

function AlertTitle({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-title"
      className={cn("col-start-2 font-medium", className)}
      {...props}
    />
  );
}

function AlertDescription({ className, ...props }: React.ComponentProps<"div">) {
  return (
    <div
      data-slot="alert-description"
      className={cn("col-start-2 leading-6 text-muted-foreground", className)}
      {...props}
    />
  );
}

export { Alert, AlertTitle, AlertDescription };
""",
    "src/components/ui/separator.tsx": r"""
"use client";

import * as React from "react";
import * as SeparatorPrimitive from "@radix-ui/react-separator";
import { cn } from "@/lib/utils";

function Separator({
  className,
  orientation = "horizontal",
  decorative = true,
  ...props
}: React.ComponentProps<typeof SeparatorPrimitive.Root>) {
  return (
    <SeparatorPrimitive.Root
      decorative={decorative}
      orientation={orientation}
      data-slot="separator"
      className={cn(
        "shrink-0 bg-border data-[orientation=horizontal]:h-px data-[orientation=horizontal]:w-full data-[orientation=vertical]:h-full data-[orientation=vertical]:w-px",
        className,
      )}
      {...props}
    />
  );
}

export { Separator };
""",
    "src/components/ui/sonner.tsx": r"""
"use client";

import { Toaster as Sonner, type ToasterProps } from "sonner";

function Toaster(props: ToasterProps) {
  return (
    <Sonner
      theme="light"
      position="bottom-center"
      toastOptions={{
        classNames: {
          toast: "bg-card text-card-foreground border-border",
        },
      }}
      {...props}
    />
  );
}

export { Toaster };
""",
    "src/components/locale-switcher.tsx": r"""
import { Languages } from "lucide-react";
import { Button } from "@/components/ui/button";
import { Link } from "@/i18n/navigation";
import { alternateLocale, type AppLocale } from "@/i18n/routing";

interface LocaleSwitcherProps {
  currentLocale: AppLocale;
  label: string;
  action: string;
}

export function LocaleSwitcher({
  currentLocale,
  label,
  action,
}: LocaleSwitcherProps) {
  const targetLocale = alternateLocale(currentLocale);

  return (
    <Button asChild variant="outline" size="sm">
      <Link href="/" locale={targetLocale} aria-label={label} hrefLang={targetLocale}>
        <Languages aria-hidden="true" className="size-4" />
        <span>{action}</span>
      </Link>
    </Button>
  );
}
""",
    "src/components/pwa/connectivity-banner.tsx": r"""
"use client";

import { useEffect, useState } from "react";
import { WifiOff } from "lucide-react";
import { useTranslations } from "next-intl";

export function nextConnectivityState(eventType: "online" | "offline") {
  return eventType === "online";
}

export function ConnectivityBanner() {
  const t = useTranslations("Pwa");
  const [isOnline, setIsOnline] = useState(true);

  useEffect(() => {
    setIsOnline(navigator.onLine);

    const handleOnline = () => setIsOnline(nextConnectivityState("online"));
    const handleOffline = () => setIsOnline(nextConnectivityState("offline"));

    window.addEventListener("online", handleOnline);
    window.addEventListener("offline", handleOffline);

    return () => {
      window.removeEventListener("online", handleOnline);
      window.removeEventListener("offline", handleOffline);
    };
  }, []);

  if (isOnline) return null;

  return (
    <div
      className="fixed inset-x-0 top-0 z-50 flex min-h-11 items-center justify-center gap-2 bg-foreground px-4 py-2 text-center text-sm text-background"
      role="status"
      aria-live="polite"
    >
      <WifiOff className="size-4 shrink-0" aria-hidden="true" />
      <span>{t("offline")}</span>
    </div>
  );
}
""",
    "src/components/pwa/service-worker-provider.tsx": r"""
"use client";

import { useEffect, useState, type ReactNode } from "react";
import { RefreshCw } from "lucide-react";
import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";
import { ConnectivityBanner } from "./connectivity-banner";

interface ServiceWorkerProviderProps {
  children: ReactNode;
}

export function ServiceWorkerProvider({ children }: ServiceWorkerProviderProps) {
  const t = useTranslations("Pwa");
  const [waitingWorker, setWaitingWorker] = useState<ServiceWorker | null>(null);
  const [showUpdate, setShowUpdate] = useState(false);

  useEffect(() => {
    if (!("serviceWorker" in navigator)) return;

    let registration: ServiceWorkerRegistration | undefined;

    const handleControllerChange = () => window.location.reload();
    navigator.serviceWorker.addEventListener(
      "controllerchange",
      handleControllerChange,
    );

    void navigator.serviceWorker
      .register("/serwist/sw.js", { scope: "/" })
      .then((nextRegistration) => {
        registration = nextRegistration;

        if (nextRegistration.waiting) {
          setWaitingWorker(nextRegistration.waiting);
          setShowUpdate(true);
        }

        nextRegistration.addEventListener("updatefound", () => {
          const installingWorker = nextRegistration.installing;
          if (!installingWorker) return;

          installingWorker.addEventListener("statechange", () => {
            if (
              installingWorker.state === "installed" &&
              navigator.serviceWorker.controller
            ) {
              setWaitingWorker(installingWorker);
              setShowUpdate(true);
            }
          });
        });
      })
      .catch(() => {
        // A failed registration must not prevent the public foundation from loading.
      });

    return () => {
      navigator.serviceWorker.removeEventListener(
        "controllerchange",
        handleControllerChange,
      );
      registration = undefined;
    };
  }, []);

  const activateUpdate = () => {
    waitingWorker?.postMessage({ type: "MITHAQ_ACTIVATE_UPDATE" });
  };

  return (
    <>
      <ConnectivityBanner />
      {children}
      {showUpdate ? (
        <div
          className="fixed inset-x-4 bottom-4 z-50 mx-auto flex max-w-xl flex-col gap-3 rounded-2xl border border-border bg-card p-4 text-card-foreground shadow-lg sm:flex-row sm:items-center"
          role="status"
          aria-live="polite"
        >
          <p className="flex-1 text-sm leading-6">{t("updateReady")}</p>
          <div className="flex gap-2">
            <Button type="button" size="sm" onClick={activateUpdate}>
              <RefreshCw className="size-4" aria-hidden="true" />
              {t("updateAction")}
            </Button>
            <Button
              type="button"
              size="sm"
              variant="ghost"
              onClick={() => setShowUpdate(false)}
            >
              {t("dismiss")}
            </Button>
          </div>
        </div>
      ) : null}
    </>
  );
}
""",
    "src/components/foundation-shell.tsx": r"""
import { LockKeyhole, ShieldCheck, Sparkles } from "lucide-react";
import { LocaleSwitcher } from "@/components/locale-switcher";
import {
  Card,
  CardContent,
  CardDescription,
  CardHeader,
  CardTitle,
} from "@/components/ui/card";
import { Separator } from "@/components/ui/separator";
import type { AppLocale } from "@/i18n/routing";

interface FoundationCopy {
  eyebrow: string;
  title: string;
  latinName: string;
  tagline: string;
  status: string;
  privacyTitle: string;
  privacyBody: string;
  directionTitle: string;
  directionBody: string;
  foundationLabel: string;
  foundationValue: string;
  languageAction: string;
  languageLabel: string;
  trustNote: string;
}

interface FoundationShellProps {
  locale: AppLocale;
  copy: FoundationCopy;
}

export function FoundationShell({ locale, copy }: FoundationShellProps) {
  return (
    <main className="relative isolate min-h-screen overflow-hidden bg-background px-4 py-6 sm:px-6 sm:py-10 lg:px-8">
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-inline-end-[-8rem] top-[-9rem] -z-10 size-80 rounded-full border border-gold/20"
      />
      <div
        aria-hidden="true"
        className="pointer-events-none absolute inset-inline-start-[-10rem] bottom-[-12rem] -z-10 size-96 rounded-full border border-primary/10"
      />

      <div className="mx-auto flex w-full max-w-5xl flex-col gap-8">
        <header className="flex items-center justify-between gap-4">
          <div className="flex items-center gap-3">
            <div className="grid size-11 place-items-center rounded-2xl bg-primary text-primary-foreground shadow-sm">
              <span aria-hidden="true" className="text-xl font-bold">
                م
              </span>
            </div>
            <div>
              <p className="text-lg font-bold leading-none text-foreground">
                ميثاق
              </p>
              <p className="mt-1 text-xs text-muted-foreground">Mithaq</p>
            </div>
          </div>
          <LocaleSwitcher
            currentLocale={locale}
            label={copy.languageLabel}
            action={copy.languageAction}
          />
        </header>

        <section className="grid items-center gap-8 py-4 lg:grid-cols-[1.15fr_0.85fr] lg:py-12">
          <div className="max-w-2xl">
            <p className="mb-4 inline-flex items-center gap-2 rounded-full border border-primary/20 bg-primary/5 px-4 py-2 text-sm font-semibold text-primary">
              <Sparkles aria-hidden="true" className="size-4" />
              {copy.eyebrow}
            </p>
            <h1 className="text-balance text-5xl font-bold tracking-tight text-foreground sm:text-6xl lg:text-7xl">
              {copy.title}
              <span className="mt-2 block text-2xl font-medium text-primary sm:text-3xl">
                {copy.latinName}
              </span>
            </h1>
            <p className="mt-6 text-xl font-semibold text-primary sm:text-2xl">
              {copy.tagline}
            </p>
            <p className="mt-5 max-w-xl text-pretty text-base leading-8 text-muted-foreground sm:text-lg">
              {copy.status}
            </p>
          </div>

          <Card className="relative overflow-hidden bg-surface/95">
            <div
              aria-hidden="true"
              className="absolute inset-x-8 top-0 h-1 rounded-b-full bg-gold"
            />
            <CardHeader className="pt-8">
              <CardDescription>{copy.foundationLabel}</CardDescription>
              <CardTitle className="text-2xl text-primary">
                {copy.foundationValue}
              </CardTitle>
            </CardHeader>
            <CardContent>
              <Separator className="mb-6" />
              <div className="grid gap-6">
                <div className="flex items-start gap-3">
                  <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">
                    <ShieldCheck aria-hidden="true" className="size-5" />
                  </span>
                  <div>
                    <h2 className="font-semibold text-foreground">
                      {copy.privacyTitle}
                    </h2>
                    <p className="mt-1 text-sm leading-6 text-muted-foreground">
                      {copy.privacyBody}
                    </p>
                  </div>
                </div>
                <div className="flex items-start gap-3">
                  <span className="grid size-10 shrink-0 place-items-center rounded-xl bg-primary/10 text-primary">
                    <LockKeyhole aria-hidden="true" className="size-5" />
                  </span>
                  <div>
                    <h2 className="font-semibold text-foreground">
                      {copy.directionTitle}
                    </h2>
                    <p className="mt-1 text-sm leading-6 text-muted-foreground">
                      {copy.directionBody}
                    </p>
                  </div>
                </div>
              </div>
            </CardContent>
          </Card>
        </section>

        <footer className="border-t border-border pt-5 text-sm leading-6 text-muted-foreground">
          {copy.trustNote}
        </footer>
      </div>
    </main>
  );
}
""",
    "src/app/globals.css": r"""
@import "tailwindcss";
@import "tw-animate-css";

:root {
  --background: oklch(0.97 0.015 89);
  --foreground: oklch(0.23 0.025 158);
  --card: oklch(0.995 0.008 88);
  --card-foreground: oklch(0.23 0.025 158);
  --popover: oklch(0.995 0.008 88);
  --popover-foreground: oklch(0.23 0.025 158);
  --primary: oklch(0.38 0.08 166);
  --primary-foreground: oklch(0.97 0.015 89);
  --secondary: oklch(0.94 0.018 91);
  --secondary-foreground: oklch(0.26 0.03 160);
  --muted: oklch(0.94 0.012 150);
  --muted-foreground: oklch(0.5 0.025 160);
  --accent: oklch(0.92 0.025 153);
  --accent-foreground: oklch(0.28 0.05 164);
  --destructive: oklch(0.5 0.16 25);
  --destructive-foreground: oklch(0.98 0.01 25);
  --border: oklch(0.88 0.02 150);
  --input: oklch(0.82 0.025 150);
  --ring: oklch(0.43 0.08 166);
  --gold: oklch(0.62 0.09 76);
  --surface: oklch(0.995 0.008 88);
  --radius: 1rem;
}

@theme inline {
  --color-background: var(--background);
  --color-foreground: var(--foreground);
  --color-card: var(--card);
  --color-card-foreground: var(--card-foreground);
  --color-popover: var(--popover);
  --color-popover-foreground: var(--popover-foreground);
  --color-primary: var(--primary);
  --color-primary-foreground: var(--primary-foreground);
  --color-secondary: var(--secondary);
  --color-secondary-foreground: var(--secondary-foreground);
  --color-muted: var(--muted);
  --color-muted-foreground: var(--muted-foreground);
  --color-accent: var(--accent);
  --color-accent-foreground: var(--accent-foreground);
  --color-destructive: var(--destructive);
  --color-destructive-foreground: var(--destructive-foreground);
  --color-border: var(--border);
  --color-input: var(--input);
  --color-ring: var(--ring);
  --color-gold: var(--gold);
  --color-surface: var(--surface);
  --radius-sm: calc(var(--radius) - 4px);
  --radius-md: calc(var(--radius) - 2px);
  --radius-lg: var(--radius);
  --radius-xl: calc(var(--radius) + 4px);
}

* {
  border-color: var(--border);
}

html {
  min-width: 320px;
  background: var(--background);
}

body {
  min-height: 100vh;
  background: var(--background);
  color: var(--foreground);
  text-rendering: optimizeLegibility;
}

html[lang="ar"] body {
  font-family: var(--font-arabic), system-ui, sans-serif;
  line-height: 1.8;
}

html[lang="en"] body {
  font-family: var(--font-inter), system-ui, sans-serif;
  line-height: 1.6;
}

::selection {
  background: color-mix(in oklch, var(--primary) 22%, transparent);
}

@media (prefers-reduced-motion: reduce) {
  *,
  *::before,
  *::after {
    scroll-behavior: auto !important;
    animation-duration: 0.01ms !important;
    animation-iteration-count: 1 !important;
    transition-duration: 0.01ms !important;
  }
}
""",
    "src/app/(localized)/[locale]/layout.tsx": r"""
import type { Metadata, Viewport } from "next";
import { notFound } from "next/navigation";
import { getMessages, getTranslations, setRequestLocale } from "next-intl/server";
import { NextIntlClientProvider } from "next-intl";
import { ServiceWorkerProvider } from "@/components/pwa/service-worker-provider";
import { Toaster } from "@/components/ui/sonner";
import { env } from "@/lib/env";
import { inter, notoSansArabic } from "@/lib/fonts";
import {
  directionForLocale,
  isAppLocale,
  routing,
  type AppLocale,
} from "@/i18n/routing";
import "@/app/globals.css";

interface LocaleLayoutProps {
  children: React.ReactNode;
  params: Promise<{ locale: string }>;
}

export function generateStaticParams() {
  return routing.locales.map((locale) => ({ locale }));
}

export async function generateMetadata({
  params,
}: Pick<LocaleLayoutProps, "params">): Promise<Metadata> {
  const { locale: candidate } = await params;
  const locale: AppLocale = isAppLocale(candidate)
    ? candidate
    : routing.defaultLocale;
  const t = await getTranslations({ locale, namespace: "Metadata" });

  return {
    metadataBase: new URL(env.NEXT_PUBLIC_SITE_URL),
    title: t("title"),
    description: t("description"),
    applicationName: "ميثاق | Mithaq",
    alternates: {
      canonical: `/${locale}`,
      languages: { ar: "/ar", en: "/en" },
    },
    openGraph: {
      type: "website",
      locale: locale === "ar" ? "ar_LY" : "en_GB",
      siteName: "ميثاق | Mithaq",
      title: t("title"),
      description: t("description"),
      url: `/${locale}`,
    },
    robots: {
      index: false,
      follow: false,
      nocache: true,
    },
    formatDetection: { telephone: false },
  };
}

export const viewport: Viewport = {
  width: "device-width",
  initialScale: 1,
  themeColor: "#0F4D3F",
  colorScheme: "light",
};

export default async function LocaleLayout({
  children,
  params,
}: LocaleLayoutProps) {
  const { locale: candidate } = await params;
  if (!isAppLocale(candidate)) notFound();

  const locale = candidate;
  const direction = directionForLocale(locale);
  setRequestLocale(locale);
  const messages = await getMessages();

  return (
    <html
      lang={locale}
      dir={direction}
      className={`${inter.variable} ${notoSansArabic.variable}`}
      suppressHydrationWarning
    >
      <body>
        <NextIntlClientProvider messages={messages}>
          <ServiceWorkerProvider>{children}</ServiceWorkerProvider>
          <Toaster />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
""",
    "src/app/(localized)/[locale]/page.tsx": r"""
import { getTranslations, setRequestLocale } from "next-intl/server";
import { FoundationShell } from "@/components/foundation-shell";
import { isAppLocale, routing } from "@/i18n/routing";

interface FoundationPageProps {
  params: Promise<{ locale: string }>;
}

export default async function FoundationPage({ params }: FoundationPageProps) {
  const { locale: candidate } = await params;
  const locale = isAppLocale(candidate) ? candidate : routing.defaultLocale;
  setRequestLocale(locale);
  const t = await getTranslations("Foundation");

  return (
    <FoundationShell
      locale={locale}
      copy={{
        eyebrow: t("eyebrow"),
        title: t("title"),
        latinName: t("latinName"),
        tagline: t("tagline"),
        status: t("status"),
        privacyTitle: t("privacyTitle"),
        privacyBody: t("privacyBody"),
        directionTitle: t("directionTitle"),
        directionBody: t("directionBody"),
        foundationLabel: t("foundationLabel"),
        foundationValue: t("foundationValue"),
        languageAction: t("languageAction"),
        languageLabel: t("languageLabel"),
        trustNote: t("trustNote"),
      }}
    />
  );
}
""",
    "src/app/(localized)/[locale]/loading.tsx": r"""
export default function Loading() {
  return (
    <main className="grid min-h-screen place-items-center bg-background px-4">
      <div
        className="size-10 animate-pulse rounded-2xl bg-primary"
        role="status"
        aria-label="Loading"
      />
    </main>
  );
}
""",
    "src/app/(localized)/[locale]/error.tsx": r"""
"use client";

import { useTranslations } from "next-intl";
import { Button } from "@/components/ui/button";

export default function ErrorPage({ reset }: { reset: () => void }) {
  const t = useTranslations("Common");

  return (
    <main className="grid min-h-screen place-items-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-2xl font-bold text-foreground">{t("errorTitle")}</h1>
        <p className="mt-3 leading-7 text-muted-foreground">{t("errorBody")}</p>
        <Button className="mt-6" type="button" onClick={reset}>
          {t("retry")}
        </Button>
      </div>
    </main>
  );
}
""",
    "src/app/(localized)/[locale]/not-found.tsx": r"""
import { getTranslations } from "next-intl/server";
import { Button } from "@/components/ui/button";
import { Link } from "@/i18n/navigation";

export default async function NotFound() {
  const t = await getTranslations("Common");

  return (
    <main className="grid min-h-screen place-items-center bg-background px-4">
      <div className="max-w-md text-center">
        <h1 className="text-2xl font-bold text-foreground">
          {t("notFoundTitle")}
        </h1>
        <p className="mt-3 leading-7 text-muted-foreground">
          {t("notFoundBody")}
        </p>
        <Button asChild className="mt-6">
          <Link href="/">{t("home")}</Link>
        </Button>
      </div>
    </main>
  );
}
""",
    "src/app/(offline)/layout.tsx": r"""
import type { ReactNode } from "react";
import { inter, notoSansArabic } from "@/lib/fonts";
import "@/app/globals.css";

export default function OfflineLayout({ children }: { children: ReactNode }) {
  return (
    <html
      lang="ar"
      dir="rtl"
      className={`${inter.variable} ${notoSansArabic.variable}`}
    >
      <body>{children}</body>
    </html>
  );
}
""",
    "src/app/(offline)/~offline/page.tsx": r"""
import { WifiOff } from "lucide-react";

export default function OfflinePage() {
  return (
    <main className="grid min-h-screen place-items-center bg-background px-4 py-10">
      <section className="w-full max-w-lg rounded-2xl border border-border bg-card p-6 text-card-foreground shadow-sm sm:p-8">
        <span className="grid size-12 place-items-center rounded-2xl bg-primary/10 text-primary">
          <WifiOff className="size-6" aria-hidden="true" />
        </span>
        <h1 className="mt-6 text-2xl font-bold">أنت غير متصل بالإنترنت</h1>
        <p className="mt-3 leading-8 text-muted-foreground">
          لا نخزّن أي بيانات خاصة للاستخدام دون اتصال. أعد الاتصال لفتح أحدث نسخة من ميثاق.
        </p>
        <div className="my-6 h-px bg-border" aria-hidden="true" />
        <div dir="ltr" lang="en">
          <h2 className="text-xl font-bold">You are offline</h2>
          <p className="mt-2 leading-7 text-muted-foreground">
            Private data is never stored for offline access. Reconnect to load the latest Mithaq experience.
          </p>
        </div>
      </section>
    </main>
  );
}
""",
    "src/app/manifest.ts": r"""
import type { MetadataRoute } from "next";

export default function manifest(): MetadataRoute.Manifest {
  return {
    name: "ميثاق | Mithaq",
    short_name: "ميثاق",
    description:
      "ميثاق — أساس عربي أولاً لتعارف خاص وجاد بغرض الزواج | Arabic-first private marriage-introduction foundation",
    start_url: "/ar",
    scope: "/",
    display: "standalone",
    background_color: "#F8F4EA",
    theme_color: "#0F4D3F",
    lang: "ar",
    dir: "rtl",
    icons: [
      {
        src: "/icons/icon-192.png",
        sizes: "192x192",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "any",
      },
      {
        src: "/icons/icon-maskable-512.png",
        sizes: "512x512",
        type: "image/png",
        purpose: "maskable",
      },
    ],
  };
}
""",
    "src/app/sw.ts": r"""
export const serviceWorkerSource = String.raw`
const CACHE_PREFIX = "mithaq-public-shell";
const CACHE_VERSION = "v1";
const CACHE_NAME = CACHE_PREFIX + "-" + CACHE_VERSION;
const PUBLIC_SHELL = [
  "/ar",
  "/en",
  "/~offline",
  "/manifest.webmanifest",
  "/icons/icon-192.png",
  "/icons/icon-512.png",
  "/icons/icon-maskable-512.png",
  "/icons/apple-touch-icon.png"
];

self.addEventListener("install", (event) => {
  event.waitUntil(caches.open(CACHE_NAME).then((cache) => cache.addAll(PUBLIC_SHELL)));
});

self.addEventListener("activate", (event) => {
  event.waitUntil(
    caches.keys().then((names) =>
      Promise.all(
        names
          .filter((name) => name.startsWith(CACHE_PREFIX) && name !== CACHE_NAME)
          .map((name) => caches.delete(name))
      )
    ).then(() => self.clients.claim())
  );
});

self.addEventListener("message", (event) => {
  if (event.data && event.data.type === "MITHAQ_ACTIVATE_UPDATE") {
    self.skipWaiting();
  }
});

self.addEventListener("fetch", (event) => {
  const request = event.request;
  const url = new URL(request.url);

  if (request.method !== "GET" || url.origin !== self.location.origin) return;
  if (
    url.pathname.startsWith("/api") ||
    url.pathname.startsWith("/admin") ||
    url.pathname.startsWith("/waitlist") ||
    url.pathname.startsWith("/account") ||
    url.pathname.startsWith("/serwist")
  ) return;

  if (request.mode === "navigate") {
    event.respondWith(
      fetch(request).catch(async () => {
        const cachedPage = await caches.match(request);
        return cachedPage || caches.match("/~offline");
      })
    );
  }
});
`;
""",
    "src/app/serwist/[path]/route.ts": r"""
import { serviceWorkerSource } from "@/app/sw";

export const dynamic = "force-static";

export async function GET(
  _request: Request,
  { params }: { params: Promise<{ path: string }> },
) {
  const { path } = await params;

  if (path !== "sw.js") {
    return new Response("Not found", { status: 404 });
  }

  return new Response(serviceWorkerSource, {
    headers: {
      "Cache-Control": "no-cache, no-store, must-revalidate",
      "Content-Type": "application/javascript; charset=utf-8",
      "Service-Worker-Allowed": "/",
      "X-Content-Type-Options": "nosniff",
    },
  });
}
""",
    "src/app/api/health/route.ts": r"""
export const dynamic = "force-dynamic";

export function GET() {
  return Response.json(
    {
      status: "ok",
      application: "Mithaq | ميثاق",
    },
    {
      headers: {
        "Cache-Control": "no-store, max-age=0",
      },
    },
  );
}
""",
    "tests/unit/i18n.test.ts": r"""
import { describe, expect, it } from "vitest";
import {
  alternateLocale,
  directionForLocale,
  isAppLocale,
} from "@/i18n/routing";

describe("locale foundation", () => {
  it("validates only supported locales", () => {
    expect(isAppLocale("ar")).toBe(true);
    expect(isAppLocale("en")).toBe(true);
    expect(isAppLocale("fr")).toBe(false);
  });

  it("maps locale to document direction", () => {
    expect(directionForLocale("ar")).toBe("rtl");
    expect(directionForLocale("en")).toBe("ltr");
  });

  it("returns the alternate locale", () => {
    expect(alternateLocale("ar")).toBe("en");
    expect(alternateLocale("en")).toBe("ar");
  });
});
""",
    "tests/unit/env.test.ts": r"""
import { describe, expect, it } from "vitest";
import { validateEnvironment } from "@/lib/env";

const validEnvironment = {
  APP_ENV: "local",
  NEXT_PUBLIC_SITE_URL: "http://localhost:3000",
  NEXT_PUBLIC_SUPABASE_URL: "http://127.0.0.1:54321",
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "publishable-test-key",
};

describe("environment validation", () => {
  it("accepts the required safe public configuration", () => {
    expect(validateEnvironment(validEnvironment)).toMatchObject(validEnvironment);
  });

  it("rejects a missing publishable key", () => {
    expect(() =>
      validateEnvironment({
        ...validEnvironment,
        NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: "",
      }),
    ).toThrow();
  });

  it("rejects an invalid site URL", () => {
    expect(() =>
      validateEnvironment({
        ...validEnvironment,
        NEXT_PUBLIC_SITE_URL: "not-a-url",
      }),
    ).toThrow();
  });
});
""",
    "tests/unit/button.test.tsx": r"""
import { render, screen } from "@testing-library/react";
import userEvent from "@testing-library/user-event";
import { describe, expect, it, vi } from "vitest";
import { Button } from "@/components/ui/button";

describe("Button", () => {
  it("is keyboard-activatable", async () => {
    const user = userEvent.setup();
    const handleClick = vi.fn();
    render(<Button onClick={handleClick}>Continue</Button>);

    await user.tab();
    expect(screen.getByRole("button", { name: "Continue" })).toHaveFocus();
    await user.keyboard("{Enter}");
    expect(handleClick).toHaveBeenCalledOnce();
  });
});
""",
    "tests/unit/locale-switcher.test.tsx": r"""
import { render, screen } from "@testing-library/react";
import { describe, expect, it, vi } from "vitest";

vi.mock("@/i18n/navigation", () => ({
  Link: ({
    href,
    locale,
    children,
    ...props
  }: React.AnchorHTMLAttributes<HTMLAnchorElement> & {
    href: string;
    locale: string;
  }) => (
    <a href={`/${locale}${href === "/" ? "" : href}`} {...props}>
      {children}
    </a>
  ),
}));

import { LocaleSwitcher } from "@/components/locale-switcher";

describe("LocaleSwitcher", () => {
  it("links Arabic to English", () => {
    render(
      <LocaleSwitcher
        currentLocale="ar"
        label="View in English"
        action="English"
      />,
    );

    expect(screen.getByRole("link", { name: "View in English" })).toHaveAttribute(
      "href",
      "/en",
    );
  });
});
""",
    "tests/unit/connectivity-banner.test.tsx": r"""
import { NextIntlClientProvider } from "next-intl";
import { act, render, screen } from "@testing-library/react";
import { beforeEach, describe, expect, it } from "vitest";
import {
  ConnectivityBanner,
  nextConnectivityState,
} from "@/components/pwa/connectivity-banner";

const messages = {
  Pwa: {
    offline: "Offline message",
  },
};

describe("ConnectivityBanner", () => {
  beforeEach(() => {
    Object.defineProperty(window.navigator, "onLine", {
      configurable: true,
      value: true,
    });
  });

  it("maps browser events to connectivity state", () => {
    expect(nextConnectivityState("online")).toBe(true);
    expect(nextConnectivityState("offline")).toBe(false);
  });

  it("announces an offline transition", () => {
    render(
      <NextIntlClientProvider locale="en" messages={messages}>
        <ConnectivityBanner />
      </NextIntlClientProvider>,
    );

    act(() => window.dispatchEvent(new Event("offline")));
    expect(screen.getByRole("status")).toHaveTextContent("Offline message");
  });
});
""",
    "tests/e2e/foundation.spec.ts": r"""
import AxeBuilder from "@axe-core/playwright";
import { expect, test } from "@playwright/test";

for (const locale of ["ar", "en"] as const) {
  test(`${locale} foundation has correct document semantics`, async ({ page }) => {
    await page.goto(`/${locale}`);
    const html = page.locator("html");
    await expect(html).toHaveAttribute("lang", locale);
    await expect(html).toHaveAttribute("dir", locale === "ar" ? "rtl" : "ltr");
    await expect(page.getByRole("heading", { level: 1 })).toBeVisible();
  });

  test(`${locale} foundation does not overflow on mobile`, async ({ page }) => {
    await page.setViewportSize({ width: 375, height: 812 });
    await page.goto(`/${locale}`);
    const dimensions = await page.evaluate(() => ({
      viewport: window.innerWidth,
      content: document.documentElement.scrollWidth,
    }));
    expect(dimensions.content).toBeLessThanOrEqual(dimensions.viewport);
  });

  test(`${locale} foundation has no serious accessibility violations`, async ({
    page,
  }) => {
    await page.goto(`/${locale}`);
    const results = await new AxeBuilder({ page }).analyze();
    const blocking = results.violations.filter(({ impact }) =>
      impact === "critical" || impact === "serious",
    );
    expect(blocking).toEqual([]);
  });
}

test("the root deterministically redirects to Arabic", async ({ page }) => {
  await page.goto("/");
  await expect(page).toHaveURL(/\/ar\/?$/);
});

test("locale switching works in both directions", async ({ page }) => {
  await page.goto("/ar");
  await page.getByRole("link", { name: /English/ }).click();
  await expect(page).toHaveURL(/\/en\/?$/);
  await page.getByRole("link", { name: /العربية/ }).click();
  await expect(page).toHaveURL(/\/ar\/?$/);
});

test("the manifest and every declared icon are available", async ({ request }) => {
  const manifestResponse = await request.get("/manifest.webmanifest");
  expect(manifestResponse.ok()).toBe(true);
  const manifest = (await manifestResponse.json()) as {
    name: string;
    display: string;
    icons: Array<{ src: string }>;
  };
  expect(manifest.name).toContain("Mithaq");
  expect(manifest.display).toBe("standalone");

  for (const icon of manifest.icons) {
    const iconResponse = await request.get(icon.src);
    expect(iconResponse.ok()).toBe(true);
  }

  expect((await request.get("/icons/apple-touch-icon.png")).ok()).toBe(true);
});

test("offline and health endpoints are safe", async ({ request }) => {
  expect((await request.get("/~offline")).ok()).toBe(true);

  const health = await request.get("/api/health");
  expect(health.ok()).toBe(true);
  expect(health.headers()["cache-control"]).toContain("no-store");
  const body = await health.text();
  expect(body).not.toMatch(/key|secret|token|database|environment/i);
});

test("the production service worker registers at the required path", async ({
  page,
}) => {
  await page.goto("/ar");
  await page.waitForFunction(async () => {
    const registrations = await navigator.serviceWorker.getRegistrations();
    return registrations.some((registration) =>
      registration.active?.scriptURL.endsWith("/serwist/sw.js"),
    );
  });
});
""",
    ".github/workflows/ci.yml": r"""
name: CI

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

env:
  APP_ENV: preview
  NEXT_PUBLIC_SITE_URL: http://127.0.0.1:3000
  NEXT_PUBLIC_SUPABASE_URL: http://127.0.0.1:54321
  NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY: ci-publishable-key

jobs:
  application:
    runs-on: ubuntu-latest
    timeout-minutes: 25
    steps:
      # TODO(M5): Pin every third-party action to a reviewed full commit SHA.
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 11.0.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm check
      - run: pnpm exec playwright install --with-deps chromium
      - run: pnpm test:e2e

  database:
    runs-on: ubuntu-latest
    timeout-minutes: 20
    steps:
      # TODO(M5): Pin every third-party action to a reviewed full commit SHA.
      - uses: actions/checkout@v4
      - uses: pnpm/action-setup@v4
        with:
          version: 11.0.0
          run_install: false
      - uses: actions/setup-node@v4
        with:
          node-version: 24
          cache: pnpm
      - run: pnpm install --frozen-lockfile
      - run: pnpm db:start
      - run: pnpm test:db
      - if: always()
        run: pnpm db:stop
""",
    "README.md": r"""
# Mithaq | ميثاق

Arabic-first technical foundation for a private marriage-introduction network serving serious adult Libyans in Libya and the diaspora.

## Milestone boundary

This branch implements **Milestone 1 only**: framework setup, bilingual routing, RTL/LTR behavior, accessible UI primitives, environment validation, Supabase client boundaries, a conservative PWA shell, tests, CI and operating documentation. It contains no registration, OTP, waitlist, member profile, matching, messaging, identity-verification or admin business flow.

## Prerequisites

- Node.js 24 LTS
- pnpm 11
- Docker Desktop or another Docker-compatible runtime for local Supabase

## Setup

```bash
pnpm install --frozen-lockfile
cp .env.example .env.local
pnpm db:start
pnpm dev
```

Use the publishable key reported by `pnpm supabase status` in `.env.local`. Never place a service-role key in a `NEXT_PUBLIC_` variable.

## Verification

```bash
pnpm icons:generate
pnpm format:check
pnpm lint
pnpm typecheck
pnpm test
pnpm build
pnpm test:db
pnpm exec playwright install --with-deps chromium
pnpm test:e2e
```

`pnpm check` runs formatting, linting, strict TypeScript, unit tests and the production build in that order.

## PWA privacy boundary

The service worker precaches only `/ar`, `/en`, the bilingual offline page, the manifest and icons. It never handles `/api`, `/admin`, `/waitlist`, `/account`, Supabase traffic or authenticated data. Every private route introduced later must trigger a cache-policy review.

## Local Supabase

```bash
pnpm db:start
pnpm test:db
pnpm db:types
pnpm db:stop
```

Milestone 1 has no application migration or fabricated database types. Generated database types become authoritative once Stage A tables are introduced.
""",
    "AGENTS.md": r"""
# Mithaq engineering boundary

- Work in explicit milestones and stop at the requested milestone.
- Arabic is the deterministic default locale; direction is rendered on the server.
- Prefer Server Components. Add Client Components only for browser interaction.
- Keep TypeScript strict; do not use `any`, `@ts-ignore` or disabled lint rules as shortcuts.
- Never expose service-role keys, OTPs, tokens, phone numbers or sensitive questionnaire data.
- User-owned data will require RLS and server authorization; neither replaces the other.
- PWA caching is allowlist-based. Re-review it before any authenticated route ships.
- Stage A business features begin only in their assigned milestone.
""",
    "docs/architecture.md": r"""
# Architecture foundation

## Runtime

Next.js App Router runs on Node.js 24. Server Components are the default; the connectivity and service-worker controls are the only foundation Client Components. Locale routing uses `next-intl` through `src/proxy.ts`, with Arabic fixed as the default and locale detection disabled.

## Boundaries

- `src/app`: routes, layouts, metadata, health and service-worker endpoints.
- `src/components`: shadcn-based primitives and composed foundation UI.
- `src/i18n`: typed locale configuration and navigation.
- `src/lib`: validated environment, fonts and Supabase client factories.
- `supabase`: local project configuration, seed boundary and pgTAP smoke test.

Milestone 3 will compose Supabase cookie refresh into `src/proxy.ts`; Milestone 1 does not simulate authentication.

## PWA

The worker is served at `/serwist/sw.js` with root scope and a conservative public-shell allowlist. It uses network-first navigation and only falls back to a precached public page. API and future private route families are explicitly excluded.
""",
    "docs/security-foundation.md": r"""
# Security foundation

- Environment variables are validated with Zod and `@t3-oss/env-nextjs`.
- The browser and server Supabase clients use the publishable key only.
- No service-role access exists in application code.
- The health response is `no-store` and exposes no configuration or database state.
- Baseline response headers disable framing and unnecessary browser capabilities.
- The PWA does not cache API, authentication or private data.
- CI uses safe dummy public configuration and read-only repository permissions.

A tested Content Security Policy, monitoring data scrubbing, bot controls, rate limiting and full production threat review are Milestone 5 work. No broad untested CSP is included now.
""",
    "docs/decision-log.md": r"""
# Decision log

| ID | Decision |
| --- | --- |
| D-001 | Arabic is the deterministic default at `/ar`; browser language does not override it. |
| D-002 | Milestone 1 includes no Stage A business feature. |
| D-003 | Supabase clients use only the publishable key; no service-role key is configured. |
| D-004 | SQL migrations and generated Supabase types will remain authoritative; no ORM is introduced. |
| D-005 | PWA caching uses a public allowlist and excludes private route families. |
| D-006 | Supabase session refresh is deferred to Milestone 3 and will be composed in `proxy.ts`. |
| D-007 | CSP is deferred until it can be tested against production integrations in Milestone 5. |
| D-008 | The current threshold/arch PWA mark is original but provisional. |
""",
    "docs/milestones.md": r"""
# Milestones

1. **Project foundation:** framework, bilingual direction, Supabase boundary, PWA shell, tests and CI.
2. **Public trust website:** marketing, privacy, safety, FAQ and policy pages.
3. **Waitlist and OTP:** adult gate, phone verification, questionnaire, consent and referrals.
4. **Admin analytics:** invitation-only MFA administration and privacy-safe aggregate reporting.
5. **Production hardening:** rate limits, CSP, monitoring, recovery, accessibility and performance acceptance.
6. **Controlled Stage A launch:** limited real-user validation and explicit Stage B gate.

Do not advance solely because code exists; each milestone requires its stated acceptance checks.
""",
    "docs/known-risks.md": r"""
# Known risks

- Current Next.js and Tailwind browser baselines may exclude older Android browsers used by part of the target market.
- Libya and diaspora SMS providers, deliverability and cost are not selected or tested.
- Legal, privacy, retention and cross-border processing review is outstanding.
- Safety escalation and moderation ownership are not assigned.
- The PWA threshold icon is provisional and requires brand review.
- Service-worker cache rules must be reviewed before authenticated routes are added.
- External font fetching during builds must be monitored; self-hosting may be preferable before launch.
""",
    "docs/deferred-features.md": r"""
# Deferred features

The following are deliberately absent from Milestone 1: phone OTP, waitlist registration, serious-intention questionnaire, consent history, referral attribution, identity documents, liveness checks, member profiles, profile discovery, compatibility scoring, introductions, decisions, matches, public or private photographs, photo watermarking, messaging, voice, calls, family accounts, moderation console, admin analytics, push notifications, subscriptions, payments, AI matching and native mobile applications.
""",
}

for relative_path, content in FILES.items():
    destination = ROOT / relative_path
    destination.parent.mkdir(parents=True, exist_ok=True)
    destination.write_text(textwrap.dedent(content).lstrip("\n"), encoding="utf-8")

print(f"Wrote {len(FILES)} Milestone 1 source files.")
